### ISSUE TITLE
databases corrupted after exiting without closing first

### ISSUE THREAD

**Issue by StefanLindow** [leifeld/dna#103]
After exiting without closing database first, the database seems to not function anymore in the following sense: Since then I can only open and recode already established codings, while newly add statements can not be filled with information, that is, the coding-statement-window does not open even though the text snippet is marked and even added to the statement list (and appear in an exported eventlist). 

This was done in MacOS 10.11.6 and dna 2.0 beta 19. Opening the database in Windows 10+dna 2.0 beta 19 makes no difference.

[diss - v3.dna.zip](https://github.com/leifeld/dna/files/1313930/diss.-.v3.dna.zip)

**Comment by leifeld** [comment]
Please try this fixed file: [diss - v3.dna.zip](https://github.com/leifeld/dna/files/1316866/diss.-.v3.dna.zip)

The problem was that there were no entries for empty (zero-string) persons, organizations, and concepts in the attribute manager. If you open the attribute manager using the middle button in the upper right corner and then going to the right-most tab within the lower panel, you can edit meta-data for the variables. For example, assign a color or type to a specific organization. The table there should usually contain an empty string entry at the top. When you click on a statement, the entry is taken from that list, and if the entry (in this case the zero-length entry) is not there, the statement cannot be opened. This is why new statements, which always start out with zero-length entries for the text variables, could not be opened. The problem was easy to fix by clicking on "add missing entries" in the attribute manager.

The question is then, however, why those entries were not there. Can you describe what you did before the problem occurred? I don't think it can be related to closing DNA without closing the file first, as DNA automatically saves each step and also closes the database before shutting down. I assume there must be a bug in some function of the software that causes these zero-length entries to disappear. Any hint would be appreciated. Did you recode before the problem occurred? Or merge databases? Or did you play with the attribute manager? Let me know if the problem occurs again and you can find out the steps leading up to the problem.

**Comment by StefanLindow** [comment]
Thank you, that helps! But unfortunately and unsatisfyingly, I already described everything I could remember having done (differently) during normal coding. I did not merge databases, but I might have done something in the attribute manager. I recall that I deleted and/or merge a few entries in one of the categories **at some point** that day - out of sense of cleaning up the mess and not knowing the crucial part of empty categories - but can not connect it to the incident. I now tried to redo some things with a copy of the file but it seems that I can not delete the empty entries anyway, so I wonder how I might have done manually.

**Comment by leifeld** [comment]
If this happens again, try to recapitulate what you did before that could have caused it and post it here. You know how to fix it now ("add missing entries"), but it would be helpful to know what is causing the problem so I can fix it. It's true that these empty entries cannot normally be deleted -- I made sure that is the case -- and that's why I'm suspecting there must be some function (perhaps the recode function?) where I forgot to block the possibility of removing empty entries.

**Comment by j-yordy** [comment]
Hi - I'm working on research as part of my PhD studies and using DNA for coding. I seem to have run into a potentially similar issue. It may have happened after I exited the program last night without closing the database first. It may have also happened as I began loading more articles in yesterday after having already coded the first set of articles loaded and I didn't notice until after closing and reopening the program. In any case the end result is seriously scrambled coding with many coded statements no longer corresponding with the correct statement text and in some cases no statement text being associated with the coding (e.g. statements 13-19). Would love some insight or advice on how to fix it so I don't have to re-do all this work, thank you!
[Protest_Emotion_COVID.dna.zip](https://github.com/leifeld/dna/files/5257929/Protest_Emotion_COVID.dna.zip)

**Comment by leifeld** [comment]
Hi there! Really sorry to hear that some sort of database problem occurred when you used DNA!

It's not really necessary to close the database before exiting the program because DNA will just close the database for you when you exit the program. Could it have happened during the import? How did you get those documents into DNA? Separately and manually using the "add new document" menu entry? I'd love to understand better what exactly went wrong, but it's sort of difficult to guess. When/if you continue to use DNA, can you try to open DNA from the command line/terminal? If you do that, it will print any error messages to the console. Or alternatively you can go to the Settings menu and click on "Redirect error messages" and select a (possibly new) text file into which all messages are written. That way, if this happens again, at least you have some error messages you can post here that might give us a better idea of what's been happening.

Can I ask for clarification on what exactly is messed up in the database? Is it just the location of the statements or anything else, such as missing documents, lost values in the statements etc?

There is a program called [DB Browser for SQLite](https://sqlitebrowser.org/). You can download it [here](https://sqlitebrowser.org/) and then use it to open the DNA database. In the "Browse Data" tab, you can select the different tables, for example DOCUMENTS, in which all documents are stored, or STATEMENTS, in which the statement locations are stored. The actual contents of each statements are stored in additional tables like DATASHORTTEXT and DATABOOLEAN. These latter tables refer to the ID of the respective statement in the STATEMENTS table, and the STATEMENTS table refers to the documents using the ID column from the DOCUMENTS table. The STATEMENTS table also contains the starting cursor and ending cursor position in the text for each respective statement.

Can you use this to check if the statements are actually referring to the right documents? Do the entries in DATASHORTTEXT refer to the right variable? You obviously know your data better than I do, so perhaps you can find any systematic patterns that would need to be recoded. It may be possible to use SQLite commands to fix/recode entries outside of DNA (and I may be able to help with that), but for that we will need to understand any systematic problems and how they would need to be fixed...

Again, sorry this happened to you. Either there is a bug somewhere, or for some reason the saving operation did not work properly (this can happen if the disk is full, if the database is lying on a network drive or in a Dropbox folder with foreign access messing with the data structure etc). Irrespective of this, please do create backups all along the way to avoid any further data loss.

**Comment by j-yordy** [comment]
Thanks for the quick response and suggestions - Using DB Browser for SQLite it appears that many of the statements are no longer associated with the correct document or the correct start/stop points (statements coded prior to the most recent upload of new documents) but so far I don't see any patterns to this. The variables themselves are still correct. I will keep looking for patterns. 

When I uploaded new files last night I used the import text files from folder function to import two folders of text files 114 and 59 text files respectively. I then began manually entering the document properties for each new import before noticing the problem after closing and reopening the program.

I'm working on macOS Mohave 10.14.3. I've changed the settings to send error messages to a text file now so that I can post error messages if it happens again. As soon as I tried to reopen the database the error message file filled up - attaching it here. 
[coding_errors.txt](https://github.com/leifeld/dna/files/5258376/coding_errors.txt)

**Comment by leifeld** [comment]
Thanks for the bug report. DNA 2.0 sometimes had a slightly error-prone way of writing into the database. DNA 3.0, which is [actively being developed](https://github.com/leifeld/dna#upcoming-release-of-dna-30), will have more reliable database access. I will close this issue as I am continuing development of that version and the bug has likely been fixed there by now.
