### ISSUE TITLE
Dependency on R 3.4.0

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#116]
Currently, `rDNA` depends on `stats (>= 3.4.0)`. This requires users of `R` 3.3 to re-install `R`. Is this really necessary? Or can we correct the dependency (and possibly others if needed)?

**Comment by JBGruber** [comment]
I haven't really checked any dependencies. I think older versions of all packages (except ggplot2) are fine though.

I'm also not sure how one even tests this. In the "R packages" book by Wickham, there is only one sentence about it. "Unless you know otherwise, always require a version greater than or equal to the version you’re currently using." So that's what I did.

I'm changing Description to stats (>= 3.0.0). If we test build this on travis, we can include older versions of R.
