### ISSUE TITLE
Manual does not compile

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#128]
Please fix and always check if it compiles properly before committing.

I also noticed that the line `\SweaveOpts{concordance=TRUE}` causes some warning window when I compile the document about the use of `Sweave` versus `knitr`. Do we need this line?

**Comment by JBGruber** [comment]
I was pretty sure I compiled it before uploading. But there was another unescaped underscore which means I apparently didn't.

I'm not quite sure what you mean by `\SweaveOpts{concordance=TRUE}`. I do not see this in the .Rnw file. Neither locally nor on GitHub. I think it is automatically added when you try compiling the manual using `Sweave` instead of `knitr`.  The document should always be compiled using `knitr` though as we use a few package which I think are not available in `Sweave`.

**Comment by leifeld** [comment]
Thanks. Ha, I installed the new Kubuntu version and forgot to switch to `knitr` in the beginning. I wouldn't have thought that it just messes with the code and inserts lines.

**Comment by davidmeiering** [comment]
Hey, I wanted to compile the manual with knitr but it is halted because it can't find the jar-file. But it is in the wd and the connection is established, so I don't have any ideas how to fix this... 

processing file: dna-manual.Rnw
  |.                                                 |   2%                     [unnamed-chunk-1]  
Quitting from lines  at lines 151-154 [unnamed-chunk-1] (dna-manual.Rnw)
Error in `dna_jar()`:
! DNA jar file could not be found in the library path or working directory. Your current rDNA version is 3.0.11.
Backtrace:
 1. rDNA::dna_init(returnString = TRUE)
 2. rDNA::dna_jar()
                                                                                                              
Execution halted

**Comment by leifeld** [comment]
This is the manual for the old DNA 2, which was last used in 2019. To compile it, you will need old versions of the packages. But I would not recommend it. Instead, go to the releases page and scroll down to 2.0 beta 25 to download a compiled PDF version. There is no manual for 3.0.11.
