### ISSUE TITLE
Split up R file in multiple files

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#130]
The `R` script with the `rDNA` functions is growing pretty long. Let's split it up in multiple files. For example:

1. `basic.R`: should contain `dna_sample`, `dna_init` etc.
2. `cluster.R`: for functions relevant to clustering and MDS
3. `network.R`: plotting networks, Hive plots, `dna_network` etc.
4. `transfer.R`: `dna_setDocuments` etc.

Or maybe subdivide by analysis and plotting? Not sure.

In the basic file, we should add some code that prints basic version and date information, like in the `btergm` and `texreg` package (copy from there).

Thoughts?

**Comment by JBGruber** [comment]
This was one of the first things I had planned to suggest because all other packages I have encountered do this. However, I never fully understood why one should separate the functions in different files and since I started working on rDNA I came to find it much easier to navigate through just one instead of multiple files. 

Take the removal of `dna_attributes` as an example. I just opened the one rDNA.R file and used search & replace to look for all instances of the function and see if it was a problem to use `dna_getAttributes` instead. In multiple files search and replace needs to be done separately for each file, taking extra time.

From a user's perspective, I can also see no upside in spreading the functions between different files. I often find myself looking through five or six different scripts on a GitHub repository before I finally find the function I'm looking for. Sometimes I have even cloned whole repositories just so I can search the content for a function. Choosing a good file structure might help with this problem but what makes sense to us might be totally confusing for an outsider.

I started a discussion on [stackoverflow](https://stackoverflow.com/q/50230499/5028841) about the topic but people shut it down because they thought it was opinion-based. The only interesting point was that multiple files could make collaboration easier, which I guess is fair but not entirely convincing to me.
