### ISSUE TITLE
Input of Data Sources into DNA

### ISSUE THREAD

**Issue by TWNorris** [leifeld/dna#141]
In our analysis, we are examining congressional hearings. Do you recommend that we separate these hearings into individual testimony/statements (i.e., multiple data sources) or keep all of the testimony/statements in a single hearing (i.e, one data source)? We are coding several hearings. Will this have any implications on the output in R?

**Comment by leifeld** [comment]
I have worked with Congressional testimony in the past. See my paper with Dana Fisher in Climatic Change. We added each testimony (i.e. each speech) as a separate document to the DNA database because we found that most convenient to work with. That also enabled us to split up the work among multiple coders more easily and remove speeches that were irrelevant. The output in R shouldn't be affected by that. At least as long as you export networks.

**Comment by TWNorris** [comment]
Thank you for the quick reply!
