### ISSUE TITLE
rDNA testthat not working when current version is not released yet

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#148]
It seems that some of the `testthat` tests fail when the current jar file version is not on the `releases` page of GitHub yet.

**Comment by JBGruber** [comment]
The jar file is built on travis using the make file before testing. It seems the problem is this change:

```
$(JAVAC) --release 8 dna/Dna.java; \
$(JAVAC) --release 8 dna/export/ExporterR.java; \
```

I think travis is using a different Java version. The resulting jar file is around 400kB smaller than my local version (you can see this towards the end of the log where `R CMD check` complains about `extdata` being 8.0Mb when it should be  8.4Mb). I suspect because above lines are skipped.

From the travis log, it looks like they are using `openjdk-7-jdk` for some reason. The command in the `travis.yml` is to install `default-jdk` via `apt`.

I tested removing  `--release 8` again, [which works ](https://travis-ci.org/JBGruber/dna/jobs/491106161). Specifying `openjdk-8-jdk` as the Java version [does not fix the problem though](https://travis-ci.org/JBGruber/dna/jobs/491109940).

Does that make sense to you? I'll have another look tomorrow.

**Comment by leifeld** [comment]
If the jar file is smaller, it probably doesn't contain the compiled Java code for DNA, only the pre-compiled libraries that are packaged along with DNA, like jdom etc.

The `--release` argument was introduced in JDK 9. Is it possible to specify (install?) `openjdk-9-jdk`, `openjdk-10-jdk`, or `openjdk-11-jdk`? They are all backward-compatible and can compile Java 8 code.

We need Java 8: On the one hand, if we compile with JDK 7, some code will not work because we use language features that were introduced with Java 8. On the other hand, if we don't provide compatibility with Java 8 and instead let it compile with a higher version, many users will not be able to use DNA because they have Java 8 installed. So the ideal solution would be to get JDK 9, 10, or 11 to work on Travis.

**Comment by leifeld** [comment]
See [here](https://stackoverflow.com/questions/49507160/how-to-install-jdk-10-under-ubuntu) for how to install JDK 11 in Ubuntu. Not sure if that applies to Travis and how it can be configured there.

**Comment by leifeld** [comment]
OK, I have fixed it. The solution was to remove the line from `travis.yml` that installs the JDK and instead add a line at the start of the file that tells Travis to use Ubuntu Xenial (instead of the default Trusty). Xenial uses JDK 11.

While looking for a solution, I came across something else that would be good to implement in the future: Travis now supports multiple build languages. We could create a build matrix (see [here](https://docs.travis-ci.com/user/build-matrix/)) and define separate requirements for building rDNA (`language: r`), DNA (`language: java`), and the manual. Then we'd get different Travis builds for the different components of the project, and DNA and the manual wouldn't be just declared as `r`. That way, it would be easier to see which parts of the project fail.

**Comment by leifeld** [comment]
PS: Testing via RStudio still fails locally on my computer, though.

@JBGruber: Can you try that on your computer and confirm? It looks like it tries to open the jar file from the source directory, not the actual library path.

**Comment by JBGruber** [comment]
Very elegant solution! I did not know it was possible to use Xenial. I tried around adding a ppa and installing JDK 11 but travis would insist on the older version.

I know about the build matrix but I have no idea how to test the Java code. At the moment we build it anyway using make and functionality is tested via R. Usually, we should get a report which test fails. In this case, I think a missing class Java error interfered with that. But yes, unit tests in Java would probably be a good idea.

To test via RStudio, you need to set the environment variable first: `Sys.setenv(MAKE_DNA = "TRUE")`. Locally, I created an `.Renviron` file which sets this at startup of the Rstudio project. I could commit it if you want.

Running `check()` is a bit different. The way it works is to first build the tarball and then test it. This works fine when the jar file is in `extdata` of the package (not the one in the library) before packaging the tarball but will otherwise fail. I think because it can't download the file either.

In the shell or in a bash script we could do something like this:

```
cd ..
make dna
cp ./output/dna-*.jar ./rDNA/inst/extdata/
cd rDNA
R CMD build .
find . -wholename './inst/extdata/dna-*.jar' -delete
R CMD check *tar.gz
```
Or in R:

```
system("cd .. && make dna && cp ./output/dna-*.jar ./rDNA/inst/extdata/ && cd rDNA")
devtools::check()
file.remove(dir(path = "./inst/extdata", pattern = "^dna-.+\\.jar$", full.names = TRUE))
```

**Comment by leifeld** [comment]
Thanks, I forgot about the environment variable. Is there any way we can set it up such that it is not required? Apart from having the separate `.Renviron` file?

I don't really understand what this `if` condition is for. I mean the one that looks for the environment variable. Can you explain under which conditions it should not be built when testing is done?

About the build matrix: I was thinking this could be done without unit testing for the Java case. Basically one build for R-devel for rDNA, one for R-release for rDNA, one build for compiling DNA successfully, and one build for compiling the manual successfully. I guess it's not super important for DNA because we indeed do that "on the way" for rDNA. But at least for the manual it could be interesting because that is currently not tested, right?

**Comment by JBGruber** [comment]
Ok, I just noticed that what I wrote earlier doesn't really make sense. The idea behind the environment variable was that it should be a switch to decide if the jar should be built or downloaded from releases for testing. But the latter one didn't work (which is your original error).

Can you test again with and without the environment variable?
