### ISSUE TITLE
Add function to dna_setAttributes allowing data frames to contain duplicates

### ISSUE THREAD

**Issue by Lana-Ollier** [leifeld/dna#175]
The possibility to rename the qualifier variable, using the function dna_setAttributes (using the attribute "concept" leads to the following error message "[Ljava/lang/Object;", "getAttributes",  : 
  java.lang.Exception: Duplicate attribute values are not permitted (ID 200 and ID 58, value "Barrier removal")" when trying to excess the new data frame using the function dna_getAttributes.  
Would it be possible to change the function so that duplicates can indeed be entered, I am using a hierarchal coding system which I wanna utilise at different levels of hierarchy and that would be a great help. Many thanks.

**Comment by leifeld** [comment]
That's right, duplicate values in short text variables are not permitted. The value itself identifies the entry. That's because in the DNA GUI, the values are displayed in a combo box, where you can select or enter the respective value. If the same value appeared in the list multiple times, the user would not know which value is being used. A simple workaround could be to just embed the structure into your coding, for example `higher-level concept/lower-level concept` and then decide during network export which level or combination you would like to retain. Another solution could be to have separate variables for the different levels; duplicates across those variables would then be allowed. You can create arbitrary variables when you create a new database. In version 3.0, you will be able to edit statement types later during the coding stage as well.
