### ISSUE TITLE
Problems in rDNA with default variable "organization" (variable1) - Change possible?

### ISSUE THREAD

**Issue by LZnsr** [leifeld/dna#187]
Hi there, 
after the connection to my DNA-database, when performing a cluster analysis through 

> clust <- dna_cluster(conn) 

as described in the current manual (https://github.com/leifeld/dna/releases/download/v2.0-beta.24/dna-manual.pdf; p. 90) or other analysis , the following error message occurs:

> Error in .jcall(connection$dna_connection, "[Ljava/lang/Object;", "getEventListColumnsR",  : 
>   java.lang.Exception: Variable 1 ('organization') does not exist in this statement type. 

I know why this message occurs: my Variable1 is defined as "person" (I have some other variables as well). I have tried to run the command as ...

> clust <- dna_cluster(conn, variable1 = "person")

   ... or some other variations of it, but without success. The same error message keeps appearing. I have also tried to add another variable named "organization" to my database, but without success.

Is there...

a) a work-around for using variable1 = "person" in all my analysis (how do I add it in the commands?) or

b) a work-around how to change the variable1 ("person") in my DNA database into your default "organization". This seems the most pratical to me. 

c) am I missing something?

This problem is related to the issue of changing the variable in network plots (https://github.com/leifeld/dna/issues/183), but your solution there worked fine with my database, but is not transferrable.

**Comment by leifeld** [comment]
Hi there. Can you post a minimal reproducible example? E.g., a small toy database with minimal data along with some `R` code that produces the error you see. That will make it easier to diagnose and fix.

@JBGruber may be able to advise further as he wrote this function.

Meanwhile, if you are able to build and install the latest build (i.e., more recent than the release version), you will find another set of functions called `dna_multiclust` and `dna_dendrogram`. This is all pretty much work in progress, and we are still thinking about which kind of user interface may be most suitable in the end. The help pages contain useful information on their usage.

**Comment by LZnsr** [comment]
Thanks for your quick response and your help! 
Here is a toy database and the code: [example_default variable.zip](https://github.com/leifeld/dna/files/3546841/example_default.variable.zip)
I hope you can retract my steps and the solution is not too difficult. 

Concerning number b) In the meantime, I figured how to rename my variable "person" to your default "organization". After this, a cluster analysis with your manual just works fine.

Nevertheless, I still would like to know how to do a cluster analysis with different variables ("person", etc.) other than your default "organization" :)

**Comment by JBGruber** [comment]
Thanks for reporting and thanks for sharing the data. This was a bug that should be fixed now. Please install the new version and try again:

```
remotes::install_github("leifeld/dna/rDNA", INSTALL_opts = "--no-multiarch")
```
As a few other things have changed since the last release, you also need 
[the new `.jar` file.](https://github.com/leifeld/dna/files/3547171/dna-2.0-beta25.zip). Please extract this into the folder you see when running this command:

```
system.file("extdata", package = "rDNA")
```

If there are any other `.jar` files in there, please delete them.

**Comment by JKerms89** [comment]
Hi,

I am reporting the same problem. I have a variable labelled "Claimant" instead of "Organisation" so most of the rDNA functions do not work. I tried JBGruber's proposed solution but to no avail. It works seamlessly with other sample datasets containing the default variable names.  I receive the following error message when I want to use the dna_barplot or dna_cluster:

Error in .jcall(connection$dna_connection, "[Ljava/lang/Object;", "getEventListColumnsR",  : 
  java.lang.Exception: Variable 1 ('organization') does not exist in this statement type.

I tried amending the code of the function beforehand to change the variable name to "Claimant" but it still did not help. I suspect there are other lines of code I need to modify/remove for the function to work. 

Can one amend variable names in the DNA database, or is there a way to change variable names within R? 

Many thanks for your ongoing help - it is greatly appreciated.

**Comment by LZnsr** [comment]
Hi JKerms89,

for the work-around of changing your "Claimant" into the default "organization" in your DNA database characteristics via R, you can try it through the following:

> dna_renameVariable(conn, statementType = "DNA Statement", variable = "Claimant", label = "organization", simulate = FALSE, verbose = TRUE)

For the other way: Reinstalling the version provided by JBGruber and deleting all the other .jar files worked well in my case as well.

Hope that helps!

**Comment by JKerms89** [comment]
Hi LZnsr,

Thank you for your explanation - both your proposed solutions seem to work now! All the best.
