### ISSUE TITLE
Merging datasets

### ISSUE THREAD

**Issue by pauclas** [leifeld/dna#202]
I'm trying to figure out how to work in the same dataset using multiple coders (some of them use Mac and others Microsoft). Before we start the coding I'm trying to test how to merge two DNA datasets. and I created two small datasets. I opened one and I'm trying to import two files from the second dataset using the document > import form DNA 2.0. I'm following the instructions in the DNA manual. However, it is taking a lot of time (more than 3 hours and still running). The only message that appears is "Importing documents and statements. (4/5) Saving statements to database ..."
I can see the statements and documents I'm trying to import. However, when I canceled the importing documents, I closed the dataset, and opened it again and the coded statements were not saved.

Am I doing something wrong? It is normal to take so long? Is there a way of knowing if there is an error? Can I merge two datasets when one was created using a Mac and the other using Microsoft?
I hope you can help me.

**Comment by leifeld** [comment]
It may take very long, unfortunately. You could leave it running over night if it's a large dataset. Make sure you redirect any error messages to a text file to see if it's stuck somewhere because of an uncaught exception. (I hope that's not the case.)

I have made this more efficient in version 3.0, which will come out this year. (You can already compile it from the sources, but I won't release it yet because the export functions and R connectivity haven't been re-implemented yet and a few minor things are still missing.)
