### ISSUE TITLE
dna_plotNetwork

### ISSUE THREAD

**Issue by pauclas** [leifeld/dna#206]
Hi,
I'm trying to create some graphs using the dna_plotNetwork option in R. 
I was able to create the graphs using the plot command but there are some options from the dna_plotNetwork that I would like to use, such as layout. I would like to know if there is a way of combining the functions of these two commands. For instance, I would like to use the alias attribute to name the nodes or I would like to set displayisolates to False. 
I would appreciate any guidance in this matter.

**Comment by JBGruber** [comment]
Hi,

`dna_plotNetwork` is a shorthand for the most common scenarios in `rDNA`. We had planned to make it a bit more universal, but unfortunately, none of us has the time at the moment.

Instead of using the shorthand, you can use `ggraph` directly thought (which is the backbone of `dna_plotNetwork`). Let me show you with a quick example and you can read more [here](https://github.com/leifeld/dna/issues/197#issuecomment-659667135):

``` r
# quick example network
library("rDNA")
dna_init()
conn <- dna_connection(dna_sample())

nw <- dna_network(conn, networkType = "onemode")
att <- dna_getAttributes(conn)

# since the sample does not come wiht an alias, I create one
att$alias <- paste("value", seq_along(att$alias))
```

To use `ggraph`, you just have to convert the `dna_network` object to an `igraph` object. To access attributes for one of the variables in the plot, you have to add them to the `igraph` object at this point. Simply use:

``` r
graph <- dna_toIgraph(nw, attributes = att)
```

`ggraph` works very similar to `ggplot2`. You build your plot up by using `geom*` functions which map data to visual representations. You can access the node data in `geom_node*` functions.

``` r
library("ggraph")
#> Loading required package: ggplot2
ggraph(graph, layout = "stress") +                               # start plot
  geom_edge_link(width = 1) +                                    # draw edges
  geom_node_point(aes(colour = color), size = 4) +               # draw nodes
  scale_colour_identity() +                                      # use color attribute to color nodes
  geom_node_text(aes(label = alias), vjust = -3, size = 2) +     # add labels
  scale_y_continuous(expand = c(0.1, 0.1)) +                     # expand scale a little to prevent cut-off labels
  scale_x_continuous(expand = c(0.1, 0.1)) +
  theme_graph()
```

![](https://i.imgur.com/5OjjaTQ.png)

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I hope that helps!

**Comment by pauclas** [comment]
Thanks so much, Johannes.
I tried to run your code using the sample dataset but I was not able to
convert the dna_network object to an igraph object including the attributes.

The error is as follows: "Error in dna_toIgraph(nw, attributes = att) :
  unused argument (attributes = att)"

If I do not include the attributes using the code below, then it creates
the object but I'm not able to add the color from the attributes later in
the graph.
graph <- dna_toIgraph(nw)

Is there any extra library that I should use?

I would appreciate your guidance on this.
Paula

**Comment by leifeld** [comment]
Tagging @TimHenrichsen

**Comment by leifeld** [comment]
I think this was solved with some updates in the meantime.
