### ISSUE TITLE
Scroll the text with a statement window

### ISSUE THREAD

**Issue by Laurencebl1** [leifeld/dna#230]
Hello, 

It is no longer possible to scroll the text when a statement or annotation window is open. It is important to be able to move in the text when a window is open. For example, if I want to make a statement, sometimes the full name of the person or organization is only written at the top of the text. If I want to make a statement at the bottom, while the statement window is open, I cannot move the page. So I have to write the name and the organization in another document to remember it and write it well afterwards. 

MacOS Monteray , Java version is Temurin 16.0.2+7 , DNA 3.0.2

**Comment by leifeld** [comment]
I think this should be the desired behavior because the popup window for the statements is a modal dialog, meaning it makes the inactive parts of the GUI unalterable temporarily.

With the default popup windows without window decoration, the recommended solution is to click beside the window to focus on the text and close the window, read the text again, then click on the statement text and enter the variable contents.

An alternative is to use popup windows with window decoration (see the Settings menu). If you have the dialog window decoration, you can freely move the popup window around and uncover the text.

**Comment by Laurencebl1** [comment]
Hi.
I can move my window, it's not a problem. I have selected the popup window frame and buttons in the settings. 
With all previous versions of DNA, I was always able to move my text up and down even when I had a statement window open. I personally find it more work to copy/paste the information into a separate document and then enter it correctly into my statement than just being able to scroll up the page. some names are sometimes difficult to write. I can't remember them to write them correctly later. Maybe it's just me. Anyway, if it's possible to do like before it would be much easier and more efficient work.

Thank you

**Comment by leifeld** [comment]
Ah, so the problem exists with popup windows with window decorations. Got it now. I will fix it straight away. I'm not sure if it will have unintended consequences, such as people forgetting to close their popup windows and then deleting the document the statement is contained in and such things, but let's see how it goes.
