### ISSUE TITLE
Order values in statement recoder

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#235]
I think it would be great if the columns in the preview window of the statement recoder could be ordered. This could be beneficial when editing multiple different values.

**Comment by leifeld** [comment]
I think this would quickly become very confusing because it would at the same time also reorder the statements that are being edited. For example, imagine you use the arrow buttons to scroll to the third statement, then you click on some column header and suddenly you are not in the third but 11th position or so after the reordering. You would immediately lose the overview of what you have already edited. Instead, I would suggest that if only certain statements are to be edited, the selection in the statement table should be adjusted before using the statement recoder.

**Comment by TimHenrichsen** [comment]
Makes sense! I'll close it
