### ISSUE TITLE
Open database in local host

### ISSUE THREAD

**Issue by alamsyah78** [leifeld/dna#244]
I try to open the sample (`sample.dna`)  using DNA 3.0. I follow these steps:

First, I create an SQLite database. No problem was found in this step (see Figure 1)
Second, I download the data sample (`sample.dna`) from Github and save it in the Documents folder. The problem is DNA 3 cannot detect files ( all files and *dna file) in the Documents folder (see Figure 2 and Figure 3)
<img width="1274" alt="Figure 1" src="https://user-images.githubusercontent.com/16342588/177207130-c6ec16db-5322-4ec4-95b9-526510f25ed0.png">
<img width="1279" alt="Figure 2" src="https://user-images.githubusercontent.com/16342588/177207141-bcb32dac-9727-4265-827d-66d8b05ab8d0.png">
<img width="1272" alt="Figure 3" src="https://user-images.githubusercontent.com/16342588/177207147-ce30bd3e-b7d1-4596-ae20-ed8a0c0e1146.png">

**Comment by leifeld** [comment]
See the discussion and solutions in #201. Does this solve your problem?

**Comment by alamsyah78** [comment]
No. I install Adopt OpenJDK version 11 with Hotspot JVM and give permission to the JAR file in the system setting. But, DNA 3.0 still does not detect my file.

Next, I create a new database (i.e., training.dna) and save it to my hard disk. I closed DNA 3. I open DNA 3.0 again and try to open training.dna file. Unfortunately, I do not find training.dna in my harddisk.

I use macOS Big Sur version 11.6.7.

Regards,

<img width="671" alt="Screen Shot 2022-07-05 at 22 02 48" src="https://user-images.githubusercontent.com/16342588/177359089-6382022f-4261-4aa9-8859-651da229b033.png">

**Comment by alamsyah78** [comment]
Thank you very much for this discussion. I will try DNA 3.0 in Windows in the future. God bless you Prof. Leifeld.

**Comment by leifeld** [comment]
Have you tried saving the dna file in another folder? Have you tried saving it in a Dropbox folder? It would be good to know these things to understand the nature of the problem better. Thanks.

**Comment by maikenmelanie** [comment]
Dear Prof. Leifeld, I have the same problem as described in this issue. I was successfully using the DNA 2.0 beta 25 version where I was always able to open the database in the local host. I recently updated my MacBook to the most recent Ventura 13.0 version and since then I am also not able to open the file anymore (undetectable as described in this issue). I tried both: opening it in the Mac file system and in a OneDrive folder, which was unsuccessful. I also checked (as described above) whether the JAR file has all the necessary permissions via the system settings (which it has).

**Comment by maikenmelanie** [comment]
Small update: Apparently the problem of not being able to see the content of some folders on my Mac does not extend to all folders, if I save the .dna file in the Pictures folder, I am able to open it in the local host.

**Comment by leifeld** [comment]
@maikenmelanie Thanks, this is a valuable hint about the Pictures folder. I found a [similar problem with a different Java application](https://forum.image.sc/t/not-able-to-open-find-files-from-mac/55404/5), and it seems to be a problem with the MacOS security settings there.

You wrote that you were using DNA 2.0 beta 25. Can you try downloading the latest version 3.0.8 and try if the problem persists there? You can use the sample.dna database for this purpose or import your 2.0 data into a new database in order to try it out. I'm happy to try to diagnose the problem if it still persists in DNA 3, but I may need your help in trying it out as I don't have a Mac to try it out on with the same issue occurring.

**Comment by leifeld** [comment]
I have fixed the MacOS problem, and the fix will be released in DNA 3.0.10 in March 2023. For now, there is a [temporary version](https://www.dropbox.com/s/k439y68p9znznzr/dna-3.0.10.e1.jar?dl=0) available. The changes in the code can be reviewed [here](60c06615362cf1a552be8c0b314923536d3f9011). Let me know if this solves the issues.

**Comment by maikenmelanie** [comment]
Thank you very much for the update. I am sorry for not getting back to you regarding your question earlier. I tried it with the new temporary version again and the issue seems to still be unresolved. I can open the dna file if it is saved in the Pictures folder, however, I cannot open it when it is saved in other folders (e.g., Documents, One Drive) although I  made sure to give the program all necessary permissions.

**Comment by leifeld** [comment]
Thanks for getting back to me. Sorry to hear it's still not working. I have only one Mac to try it out with, and it worked there after making the changes. To diagnose the problem better, would you mind opening DNA, going to the message log (click on the little bug in the lower right corner, export the log as a JSON file, and post it here? That should include the operating system type, which is used to decide which file chooser to use. Thanks.

**Comment by maikenmelanie** [comment]
Yes, sure you can find the JSON file attached, hope it helps. 
[messagelog_dna_maiken.json.zip](https://github.com/leifeld/dna/files/10821769/messagelog_dna_maiken.json.zip)

**Comment by leifeld** [comment]
Thanks, much appreciated. I have an idea what may have gone wrong. Would you mind trying it with [this new temporary version](https://www.dropbox.com/s/a9udqdjpmyzuwhw/dna-3.0.10.e2.jar?dl=0)? Thanks.

**Comment by maikenmelanie** [comment]
Now I can navigate in my folders to the file location as I have been able to before, this is great. Yet, I get the following message when trying to open the DNA file: 
<img width="631" alt="Bildschirm­foto 2023-02-24 um 10 53 33" src="https://user-images.githubusercontent.com/57909259/221148614-a5ce9f99-62e3-449d-9ab2-a049d6300dbf.png">
[dnalog_maiken.json.zip](https://github.com/leifeld/dna/files/10822879/dnalog_maiken.json.zip)

**Comment by leifeld** [comment]
Great! Yes, I noticed in the error log you sent that there was an uncaught error message about not being able to find some of the required tables in the database. My best guess was that you were trying to open a database created in DNA 2.0 with DNA 3.0. This is not possible because the data structures have changed. So I have now added a proper error message when that happens. If you click on the little bug symbol in the lower right corner of the DNA window, you can will be able to see the full error message with version numbers and instructions. The good news is that there is an import function that is compatible with version 2 databases. You basically have to create a new database, set up any required coders, and then use the "Import from DNA database" dialog in the "Documents" menu to copy all the documents, statements etc into the new database. This works with database version 2 and 3.

**Comment by maikenmelanie** [comment]
Thank you very much for checking the error message and for your time and effort in general, this is great.

**Comment by leifeld** [comment]
Happy to help. I'll close this as fixed.
