### ISSUE TITLE
Problem with unidentified character in text

### ISSUE THREAD

**Issue by rubensyanes** [leifeld/dna#283]
Hi!
I am using DNA2.0 because I need to upload several tweets as documents.
In some messages, when I duplicate a statement, I am not able to open the window to add the new concept neither clicking on the selected text or on the recently added statement in the left. I am not sure why this happens? I have tried different alternatives without success. 1) identify special characters that could be creating the problem, 2) dividing my documents in smaller sets. 
Any hints about what could be happening?

Thanks in advanced

**Comment by leifeld** [comment]
At this point, I would recommend DNA 2.0 only for setting up the initial database, and then I would import this into a new DNA 3.0 database before doing any coding. Is there any reason you need to code in DNA 2.0?

**Comment by rubensyanes** [comment]
Nop... i´ll try that...
Thanks

**Comment by leifeld** [comment]
DNA 3 is generally less error-prone regarding data saving, so hopefully this will fix the problem. It's difficult to tell now what the problem in DNA 2 is. But even if you started it from the command line and recorded the error message, I might not be able to fix the bug in DNA because my efforts are focused on DNA 3 now. Let me know how you get on and if this fixes your problem.

**Comment by leifeld** [comment]
Feel free to join the Matrix DNA space if you want to chat about any follow-up questions. See the README on the main page for details. I'll close this here now.
