### ISSUE TITLE
Can't delete or add new statements on Discourse Network Analyzer (DNA)

### ISSUE THREAD

**Issue by KlaudiaKoxha** [leifeld/dna#284]
[SQL] Failed to delete statement(s) from database.

[SQL]  └─ Failed to add statement to Document 6.

**Comment by leifeld** [comment]
Which DNA version?

Local or remote database?

Is this a permanent issue with the database, or has it happened once?

**Comment by KlaudiaKoxha** [comment]
Version 3.0.10. 
It's actually a copy of the database that I created and saved it on internal. I wanted to experiment some changes on a copy first. Just happened today when I opened the files. I'm receiving errors every time I want to delete or add a statement.

**Comment by leifeld** [comment]
Is this happening both with the copy and the original? Are they saved on the same drive?

I'm happy to take a look if you want to send the database to me by email. But at the moment at least it sounds more like an operating system or file system or connection issue.

**Comment by KlaudiaKoxha** [comment]
I just checked. It works fine in the original. I'll take it from there. 
However, is there a way I can still resolve this issue with the copies of the database? Does it depend on the location where I save the files? 

Thank you so much for your help!

**Comment by leifeld** [comment]
It shouldn't be happening, but I have seen some weirdness with file permissions occasionally, especially on MacOS. Are you using an Apple device, by any chance?

What's the directory you saved the copy in? Maybe that can provide a clue.

Have you tried copying the copy of the database to the location of the original database and opening it from there? That way, we can find out if the problem is caused by the file or the directory.

**Comment by KlaudiaKoxha** [comment]
Yes, it's an Apple computer. 
Indeed, I changed the directory after some weird disruptions with another QDA software and I read it's best to save files on Internal.

**Comment by leifeld** [comment]
Great! I take it the problem has disappeared now with the change of directory. If the problem persists, please feel free to re-open this issue.
