### ISSUE TITLE
Bug exporting network

### ISSUE THREAD

**Issue by viniciussferraz-unesp** [leifeld/dna#296]
Hi!

I'm having a problem when I try to export a network. I'm running some tests for a bigger analysis that Ia have to do, but once I put any variable as an author, I can't export the extension .graphml to the console, as the image shows. What should I do? Thanks.

<img width="830" alt="Screen Shot 2024-09-13 at 15 26 48" src="https://github.com/user-attachments/assets/6e19a7c7-e0c5-4b5e-bf1f-9f05aac496b4">

**Comment by leifeld** [comment]
Hi there. This seems to be a duplicate of #279. Just to double-check, are you trying to use the author field, which is a document-level variable, or were you actually thinking of using the person or organization variable? I'm asking because somebody else got confused by that recently. I'll close the issue here to have the discussion bundled in one place over at #279. I'll aim to fix this problem by the end of the month and release a new version early next month.

**Comment by viniciussferraz-unesp** [comment]
Hey, Philip. Thanks for the reply. So, Do I need to wait for the next version of the software? I'm in the middle fo my ongoing thesis, analyzing the data, so please, let me know. Thanks.

**Comment by leifeld** [comment]
It took long enough, but this bug has now been fixed. The bugfix will be included in the next release at the end of this month (DNA 3.1.2). It was fixed in commit https://github.com/leifeld-lab/dna/commit/abd1cc831d01ae073bf644ac02e710ef7f15c9af. It was a problem in the visone graphml export function, which tried to look up attributes and colours for the entities; but with document-level variables, there are no attributes or colours, so it failed in those cases.
