### ISSUE TITLE
Right to left

### ISSUE THREAD

**Issue by ytoly** [leifeld/dna#44]
Hi
Thanks for this great tool. We have just started using it and it seemed to be the one we where looking for.
One problem though, we are analyzing Hebrew text - right to left data, and the copied text is aligned to the wrong side. 
We would really appreciate if you can add a check-box to mark the text as right to left and change the alignment.

Thanks
Jonathan

**Comment by leifeld** [comment]
I've been playing with right-to-left text orientation, but it's not so easy. I have managed to...

1. put the scroll bar on the left,
2. make the text ragged left,
3. change the direction of the text itself from right to left.

But if I do that, the highlighted text portions will still show up from left to right within the right-to-left text, and presumably I'll also have to recompute the coordinates of the statements in terms of caret positions somehow. If anyone is willing and able to assist with this, that would be great. Otherwise I'm not sure how to implement this properly. I basically need to know what the exact requirements are, for Hebrew but also potentially other languages (do they all work in the same way or do they have different requirements?). Any volunteers, please respond to this thread. Thanks.
