### ISSUE TITLE
Show statement IDs of copied statements

### ISSUE THREAD

**Issue by brandenberger** [leifeld/dna#59]
In the edit window to code a statement: show IDs of all the other statements that have been cloned from this statement. This would make it easy to switch to the same statements and recode them if a mistake has been made. 

E.g.:
step1: mark a statement and code it
step2: copy said statement and change for instance the actor
step3: coder realizes they made a mistake on the issue (for both statements). By clicking on the statement, only one statement-edit-window appears and you can only change 1 of the statements. It would be simpler if you could click on a link that opens up all the other statement-edit-windows that were cloned from the original one.

**Comment by leifeld** [comment]
Isn't this possible using the "current" option in the statement navigator in the sidebar? See the attached screenshot. I find it relatively easy to navigate between duplicates within a document by displaying only statements in the current document, especially because they are always ordered by location in the text, so they are by definition grouped together in the list.

![screenshot - 20 04 2015 - 19 35 26](https://cloud.githubusercontent.com/assets/5451293/7236324/8db296e4-e794-11e4-82ca-117bc4d746ed.png)

**Comment by leifeld** [comment]
Closed because there was no further reply and interest in the topic.
