### ISSUE TITLE
Statement interface not working

### ISSUE THREAD

**Issue by aleipold** [leifeld/dna#73]
If you try to add some characteristics to a certain statement (e.g. person name, organziation etc.) there is no interface showing up. Tested under Java v8/101.

**Comment by leifeld** [comment]
Using what DNA version? Please see the 'about' window.

**Comment by aleipold** [comment]
2.0 beta 14

**Comment by leifeld** [comment]
Did you create the dna database using that version or a prior version?

**Comment by aleipold** [comment]
I created a new database, marked some passages and tried to edit them via clicking, but nothing further happened. I've created the db as administrator.

**Comment by leifeld** [comment]
What error messages are printed on the terminal? You can redirect any output to a text file (in the settings menu) if that helps. Can you attach an example database where this happens?

**Comment by aleipold** [comment]
Unfortunately I am not able to produce any error message. I've uploaded the example dna-file on to sendspace since GitHub won't allow to attach this file type (see: https://www.sendspace.com/file/l60eoq). Plus: I am not able to produce any network export, possibly due to the failure in adding any characteristics to the marked statement. -- Maybe the initial error occured while I created the database. I will create a new one.

**Comment by leifeld** [comment]
Try the new [beta 15](https://github.com/leifeld/dna/releases/tag/v2.0-beta.15). It should work with new files. With your existing file, you can click on the "Add missing" button in the new attribute manager at the bottom.

**Comment by aleipold** [comment]
Thanks a lot for your immidiate response and the new beta version! I will give it try as soon as I am back on my working station.

**Comment by aleipold** [comment]
Ran a new database today and the statement function worked perfectly well. Thanks, issue is resolved.

**Comment by leifeld** [comment]
Awesome! Thanks for checking it out.

**Comment by malkamont** [comment]
Hello Philip,

I've been using DNA without problems for quite some time, until recently I think that I encountered this bug with the statement interface.

Using the latest version of DNA, everything had been working correctly until I added a small batch of raw text files to the database. Now, the interface will pop up **only** when creating new statements, This means that I can't edit the old ones anymore. The bug remains even if delete the files that I imported.

The file has been worked by several people over the years and I'm not sure on which version of the DNA it was originally created. Here's my current setup:

DNA version: 2.0 beta 25 (2019-09-08)
Java version: 1.8.0_312
Operating system: Windows 10 10.0

I wonder if there's a way to somehow make the file work properly again as the bug persists even if I import the data into a brand new DNA file?

I'll send the file via [funet filesender](https://helpdesk.it.helsinki.fi/en/instructions/saving-and-sharing/funet-filesender/funet-filesender) to philip.leifeld@essex.ac.uk. In this file, the 'test' statement (ID 3167) is working correctly, but the interface won't pop up for any of the other statements on my computer. The software isn't printing any error messages either.

**Comment by leifeld** [comment]
Hi Arttu! Thanks for sending your file.

It looks like the attribute entries are missing for most of the values found in your statements. If you open the attribute manager in the bottom panel, you will see that for none of the three variables (person, organization, concept) any values except `TEST` exist. This is strange and certainly shouldn't be that way because DNA usually keeps the attributes and the values used in any statements in sync.

You can open the attribute manager by first clicking the middle button of the three buttons in the upper right corner of the DNA window in order to open the bottom panel. Then, in the bottom panel, you can click the right button of the three buttons displayed in the top right corner of the bottom panel. Once you see the attribute manager, you need to select DNA statements in the left combo box and then the respective variable in the right combo box at the top of the bottom panel. You will see that none of the persons, organisations, or concepts show up there. That's the problem.

The solution is actually fairly simple: Click on the button `Add missing entries`. This will check for all the values used throughout the file and put them into the table. Do this three times, once for each of the three variables. Then you should be able to access your statements again.

As I said, I am unsure what caused it. But I won't look into the source of the problem because I am already working on a new DNA 3.0 interface that shouldn't have any of these issues anymore. I am hoping I will be able to release it by the summer, but let's see how things work out.

Let me know if this worked for you.

**Comment by malkamont** [comment]
Hi Philip,

Many thanks for your prompt response and guidance - this fixed the problem!

Nice to hear that the DNA is still under active development- I'm looking forward to working with DNA 3.0 in the future.

Best,
Arttu
