### ISSUE TITLE
Add a 'save as' function to the file menu

### ISSUE THREAD

**Issue by ma19fr** [leifeld/dna#89]
The auto-save function is not always helpful - especially if you can not choose a different file to save-as in the beginning. 

Maybe it is possible, that DNA saves the file in a backup-file and before you close a it, DNA asks to save it separately.

**Comment by ma19fr** [comment]
Thank you for the detailed answer - that all makes sense! 
I wasn't thinking about multiple users and didn't use a SQL database before... 

Still, I think a save-as function could be helpful (especially if you are not working with multiple users). 

Is it possible to add an undo-function? That would help a lot (sometimes) and would relativize the auto-save function.

**Comment by leifeld** [comment]
OK, I'll take note of the 'save as' function and implement it when I'm done with some of the other stuff.

An undo function would be great, but it is a hell of a lot of work to create, so I won't prioritize this for now. I think it's more important to get the export functions up to speed right now. There was a previous issue (#26) on the topic of undo/redo functionality, but already then I decided it was too much work and shouldn't be prioritized. To implement it, one would basically have to write a class that represents all actions (such as adding or deleting a document, updating meta-data, adding/deleting/modifying coders, updating the attribute manager, adding/deleting/updating statements etc.) in an abstract way, and then build a data structure where these instances are put on two different stacks, one for committing them and one for reverting them. So that would really require some thorough changes...

**Comment by leifeld** [comment]
DNA 3.0 is [in preparation](https://github.com/leifeld/dna#upcoming-release-of-dna-30). I have revisited the issue while redesigning the architecture of DNA. Unfortunately, it does not seem like a viable option at this point. It would not be practical for multiple coders, and DNA 3.0 focuses on this using remote databases. It also creates much bigger complexity in the code. I made a first attempt at implementing an event stack for any database changes in order to make them accessible for undo, redo, and save functions. But it got so complicated in the end that it was just not worth it.

However, there are two other new functionalities that may at least mitigate the problem somewhat. First, in DNA 3.0 it will be possible to show window decoration around the statement popup windows, which means you can save or cancel changes in statements. This should come in handy if you start editing a statement and then forget what was previously written in one of the variables. In that case, you can just cancel and get the old value back. Second, there will be a message log. It records all database changes you make, and you should be able to look at this record to see when you did what. It's possible to export the log file in XML or JSON format as well. So not quite what you are asking for, but perhaps helpful.
