### ISSUE TITLE
visone export: changing edge color or width makes edges become invisible in visone

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#94]
Tested with DNA 2.0 beta 18.

**Comment by aleipold** [comment]
Could you please spefify the problem. I just exported a graphml-file from visone into pdf on the basis of the sample.dna-file. And I changed the edge-colour in visone beforehand. everything looks quite normal.

**Comment by leifeld** [comment]
It happened with a graphml file I'm working with here. I need to explore the issue further and will do so asap. I don't remember if it happened after changing the line color or rather line width, but it was visible immediately in visone (i.e., I didn't need to export it). It's possible to fix it in visone in the edge property tab, but it's a bit annoying, so I'll look into this.

**Comment by aleipold** [comment]
Okay, I just ran another test. This time I added one more statement to the sample.dna-file, exported a one-mode network into graphml and re-arranged in visone. firstly, I change the layout (backbone). Then I added weighted link width and reshaped the node size as well as the node heigth (in both cases related to frequency). Last, not least I added some group layer (girvan newman) and exported everything into pdf and png-files. In order to avoid bias due to the sample-dna.file I build up another dna-file and undertook the same procedure: everything worked well, except attributing color to actors in my dna-file. So, I am eager to hear from you :+1:

**Comment by leifeld** [comment]
This seems to be a bug in `visone` rather than `DNA`. Sometimes when the user selects multiple edges at once and changes the line width, the color of the edges is deleted. The edges are still there, but they are invisible since they don't have a color. The user then needs to select the colorless edges again and set their color in the edge properties window. I have not been able to identify the conditions under which this happens. Sometimes it does and sometimes it doesn't happen. However, it does not seem to be related to the way `DNA` is exporting `graphml` files. So I'll close this issue for now.
